name: Test Source Code Formatting

on: ['push', 'pull_request']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: install clang format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: test if formatting is appropriate
      run: make formatcheck
