name: Build and Test

on:
  push:
    tags:
      - "!v*"
    branches:
      - "**"
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/build_test.yml

  static:
    uses: ./.github/workflows/format_static.yml
