name: Generate Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/build_test.yml

  static:
    uses: ./.github/workflows/format_static.yml
  
  rpmbuild:
    runs-on: ubuntu-latest
    needs: ["tests", "static"]
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "ppc64le"]
        os: ["el8", "el9", "f37", "f38", "rawhide"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # TODO: maybe this doesn't need to be matrixed so it can be cached?
      - name: prepare qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "${{ matrix.arch }}"

      - name: build docker image
        run: docker build -t ${{ matrix.os }}-${{ matrix.arch }} --platform linux/${{ matrix.arch }} -f ci/Dockerfile.${{ matrix.os }} .

      - name: run docker build
        run: docker run -t --platform linux/${{ matrix.arch }} -v $(pwd):/build ${{ matrix.os }}-${{ matrix.arch}} bash -c "cd build && ci/build.sh"

      - name: upload rpms
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: rpms/*

  release:
    runs-on: ubuntu-latest
    needs: rpmbuild
    steps:
      - name: download rpms
        uses: actions/download-artifact@v3

      - name: generate release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref_name, 'rc') }}
          files: |
            */*.rpm