name: x86 Make CI

on: ['push', 'pull_request']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: install openssl and valgrind for running test script
      run:  sudo apt-get update && sudo apt-get install -y openssl valgrind libssl-dev libmbedtls-dev cppcheck cmake

    - name: run cppcheck
      run: make cppcheck

    - name: run test cases
      run: make check

    - name: run and test cmake builds
      run: |
        cmake -Bbuild . -DUSE_ASAN=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build build
        make check SECVAR_TOOL=$(pwd)/build/secvarctl
        
  
