name: x86 Make CI

on: ['push', 'pull_request']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install openssl and valgrind for running test script
      run:  sudo apt-get update && sudo apt-get install -y openssl valgrind libssl-dev libmbedtls-dev cppcheck

    - name: run cppcheck
      run: make cppcheck

    - name: run test cases
      run: make check

    # TODO: Disabled until cmake build returns
    # - name: run and test cmake builds
    #   run: |
    #     sudo apt install cmake
    #     mkdir build
    #     cd build
    #     cmake ../ .
    #     cmake --build .
    #     mv  secvarctl ../secvarctl-cov
    #     cd ../test
    #     make
    #     make clean 
    #     cd ../build
    #     rm -r *
    #     cmake ../ -DOPENSSL=1 .
    #     cmake --build .
    #     mv  secvarctl ../secvarctl-cov
    #     cd ../test
    #     make OPENSSL=1
    #     make clean
    #     cd ..
        
  
