name: x86 Make CI

on: ['push', 'pull_request']

jobs:
  makefile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: install openssl and valgrind for running test script
      run:  sudo apt-get update && sudo apt-get install -y openssl libssl-dev libmbedtls-dev

    - name: run test cases
      run: make check

  cmake:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: install openssl and valgrind for running test script
      run:  sudo apt-get update && sudo apt-get install -y openssl libssl-dev libmbedtls-dev cmake

    - name: generate cmake build
      run: cmake -Bbuild . -DUSE_ASAN=ON -DCMAKE_BUILD_TYPE=Debug

    - name: run cmake build
      run: cmake --build build

    - name: run test cases
      run: make check SECVAR_TOOL=$(pwd)/build/secvarctl
